# Model-wide constants, shared across all hardware configs (always loaded).

# APPLICATION CHARACTERIZATION THRESHOLDS
MEM_BW_THRESHOLD_L=0.03
MEM_BW_THRESHOLD_U=0.33
MEM_LAT_THRESHOLD_L=0.01
MEM_LAT_THRESHOLD_U=0.2
L1_BW_THRESHOLD_L=0.5
L1_BW_THRESHOLD_U=1.0
L2_BW_THRESHOLD_L=0.1
L2_BW_THRESHOLD_U=0.75
L2_LAT_THRESHOLD_L=0.05
L2_LAT_THRESHOLD_U=0.5
MIXED_MAX_WEIGHT=0.5
########
CACHE_LINE_SIZE=64
PTR_SZ=8
CPU_FREQ_GHZ=2.4
LPF_LAT=1.5                # 2
LPF_BW=3                  # 10

FIRST_ACCESS_DEMAND_HIT_PERCENTAGE=0.875
OTHER_ACCESS_DEMAND_HIT_PERCENTAGE=0.875

# VERBOSE...[0-3]
VERBOSE=1
