# SST-simulated machine = Intel Xeon Bronze 3106 (8c @ 1.70 GHz)
L1_BW=62                       
L2_BW=52                        
LOCAL_MEM_BW=73                
LOCAL_MEM_LAT=110
MPI_RECV_LAT=320
MPI_RECV_BW=9444000000          # 9444*1000000
CXL_REMOTE_LAT=350
CXL_REMOTE_ATOMIC_LAT=430
ADDED_UNPACK=True
